# Generated by Django 4.2.4 on 2023-09-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_description_listings_owner_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='highest_bidder',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
