# Generated by Django 4.2.4 on 2023-10-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_highest_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
