# Generated by Django 4.2.4 on 2023-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_photo_alter_listings_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
