# Generated by Django 4.2.4 on 2023-10-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(default='others', max_length=100, verbose_name=''),
        ),
    ]
